server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 129.28.169.156:8848

service-url:
  nacos-user-service: http://nacos-payment-privider   #调用的服务
